### ISSUE TITLE
Bulk renaming Atlas definitions

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ROhdsiWebApi#11]
A general convention for naming cohorts is with a prefix such as [prefix details]. Prefixes start with '[' and end with ']'. Inside the prefix is some meaningful classification of the project.

It would be nice to have a function that is allows for 
- searching cohorts that meet a certain string (or regex) inside the prefix
- be able to bulk change prefix from '[ABC]' to [DEF]' with some form of confirmation notification/warning.

**Comment by alondhe** [comment]
So we'd add:
getCohortsByPrefix: this would essentially pull back the cohort list and then use grep or something to handle regex searching. 

For bulk changing the prefixes, I'm not sure this is a good idea, especially with security not fully enabled. @anthonysena and @chrisknoll -- what are your thoughts?

**Comment by gowthamrao** [comment]
@chrisknoll @anthonysena  @alondhe I think its reasonable to wait till security is fully validated/enabled/implemented.

**Comment by gowthamrao** [comment]
User may filter returned object from this function https://github.com/OHDSI/ROhdsiWebApi/issues/40

**Comment by gowthamrao** [comment]
We are now able to get a list of atlas definition details (including names) as R-dataframe. This object may be filtered based on prefix etc.
Bulk renaming is still pending
To do that we have to solve posting definitions as described here
https://github.com/OHDSI/ROhdsiWebApi/issues/42

**Comment by schuemie** [comment]
I for one am very uncomfortable in programmatically pushing changes to WebAPI. It is too easy to make mistakes, with no easy recovery options.

I would prefer it if ROhdsiWebApi viewed WebAPI as read-only. The way I deal with the prefixes is after I get the information from WebAPI, for example as demonstrated [here](https://github.com/ohdsi-studies/Covid19CohortEvaluation/blob/master/extras/GrabInitialSetOfCohorts.R#L16).

In my opinion, the prefixes are an workaround made necessary because ATLAS doesn't use the notion of projects. Ideally, all this will go away in ATLAS v3.0.

**Comment by gowthamrao** [comment]
> Bulk renaming is still pending
To do that we have to solve posting definitions as described here

We have solved posting definitions. But we wont be solving 'bulk renaming' based on @schuemie  comment above.
