### ISSUE TITLE
[BUG] Failed Release of Version 1.3.0

### ISSUE THREAD

**Issue by TheCedarPrince** [OHDSI/ROhdsiWebApi#239]
@chrisknoll - I saw that you merged a PR for releasing version 1.3.0 of ROhdsiWebApi here: #237 

Somehow, it does not seem to have properly tagged in the release.
I tried using it and only installed 1.2.1 at first and had to manually install from master via `remotes::install_github("OHDSI/ROhdsiWebApi")` to get the most recent version.
Just wanted to give a heads-up!

**Comment by chrisknoll** [comment]
Something happened with the release when the branch was pushed to master: the dev branch passed tests, but master didn't. I'm trying to figure out why.

**Comment by schuemie** [comment]
I recommend just rerunning the action. The cause if probably some issue with the testing webApi? I normally see a button "Rerun all jobs" (see screenshot below). I don't see that here, possible because I didn't create the pull request. @chrisknoll : could you give this high priority? Currently we're in a bad state, where the head of master is not tagged.

![image](https://user-images.githubusercontent.com/6713328/149793180-a2a1d694-5f93-4965-973d-da1af3b97179.png)

**Comment by schuemie** [comment]
Some of the unit tests were failing, and they were also failing on my local machine, so I disabled them, allowing the release process to finish.

@gowthamrao : you're the package maintainer. Please, next time something goes wrong during package release, do not leave it in a corrupt state, but fix it **immediately**.
